version: "3.7"
services:
  clutch_database:
    build:
      #context: /cp/capital-pipelines_rest_api_db/project_explorer
      context: .
    depends_on:
      - db
    container_name: clutch_database
    restart: always
    ports:
      - 49002:49002

  db:
    environment:
      POSTGRES_USER: fraxses
      POSTGRES_PASSWORD: fraxses
      POSTGRES_DB: clutch
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data 
